blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from catalog.views import ProductListView, ProductDetailView, ContactView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, category_list
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('categories/', category_list, name='category_list'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=200, verbose_name='Описание')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"
        ordering = ['name']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.CharField(max_length=200, verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='product_images/', verbose_name='Изображение (превью)', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    owner = models.ForeignKey(User, verbose_name='Владелец', help_text='Укажите владельца продукта', on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = "Продукты"
        permissions = [
            ('can_edit_product', 'Can edit product'),
            ('can_edit_description', 'Can edit description'),
            ('can_edit_is_published', 'Can edit is_published')
        ]

    def __str__(self):
        return f'{self.name}, {self.price}'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='versions', verbose_name='Продукт')
    version_number = models.CharField(max_length=50, verbose_name='Номер версии')
    version_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current = models.BooleanField(default=False, verbose_name='Текущая версия')

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return f'{self.product.name} - {self.version_number}'

    def save(self, *args, **kwargs):
        if self.is_current:
            Version.objects.filter(product=self.product).exclude(id=self.id).update(is_current=False)
        super().save(*args, **kwargs)

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory

from .models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'price', 'category', 'image', 'is_published')

    def clean_name(self):
        name = self.cleaned_data['name']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in name.lower():
                raise ValidationError(f'Слово "{word}" запрещено в названии продукта.')
        return name

    def clean_description(self):
        description = self.cleaned_data['description']
        forbidden_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in forbidden_words:
            if word in description.lower():
                raise ValidationError(f'Слово "{word}" запрещено в описании продукта.')
        return description


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ('description', 'category', 'is_published')


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ['version_number', 'version_name', 'is_current']

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Version
from catalog.services import get_categories


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    permission_required = 'catalog.view_product'
    template_name = 'catalog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        product_versions = {}
        for product in products:
            active_version = Version.objects.filter(product=product, is_current=True).first()
            product_versions[product] = active_version
        context['product_versions'] = product_versions
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    permission_required = 'catalog.view_product'
    template_name = 'catalog/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object
        return context


class ContactView(LoginRequiredMixin, TemplateView):
    template_name = 'catalog/contact.html'


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:index')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)
        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        if formset.is_valid():
            formset.save()
        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.has_perm('catalog.can_edit_product') or user.has_perm(
                'catalog.can_edit_description') or user.has_perm('catalog.can_edit_is_published') or user.is_superuser:
            return ProductForm
        raise PermissionDenied

    def dispatch(self, request, *args, **kwargs):
        if (request.user != self.get_object().owner and not request.user.is_superuser and not request.user.has_perm('catalog.can_edit_product')
                and not request.user.has_perm('catalog.can_edit_description') and not request.user.has_perm('catalog.can_edit_is_published')):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')
    template_name = 'catalog/product_confirm_delete.html'

    def test_func(self):
        return self.request.user.is_superuser


def category_list(request):
    categories = get_categories()
    return render(request, 'catalog/category_list.html', {'categories': categories})

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                </div>
                {% include 'catalog/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="/" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Продукты</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-md-12">
    <h2>Список категорий</h2>
    <ul>
        {% for category in categories %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <p class="card-text">
                    Офис МСК<br>
                    Офис СПБ
                </p>

                </form>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h2>Напишите нам</h2>
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control mb-2" name="name"/>
                    <input class="form-control mb-2" name="email"/>
                    <textarea class="form-control mb-2" name="message"></textarea>
                    <button type="submit" class="btn btn-primary form-control">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load static %}
{% load media_tags %}

{% block content %}
    <div class="col-12 mb-5">
        {% if user.is_authenticated %}
            {% if perms.main.add_product %}
                <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Добавить продукт</a>
            {% endif %}
        {% endif %}
    </div>

    <div class="row">
        {% for product in object_list %}
            {% if product.is_published %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h4 class="card-title">{{ product.name }}</h4>
                            {% if product.description %}
                                <p class="card-text">{{ product.description|slice:":100" }}</p>
                            {% endif %}
                            {% with product_versions|get_active_version:product as active_version %}
                                {% if active_version %}
                                    <p class="card-text"> {{ active_version.version_name }}
                                        ({{ active_version.version_number }})</p>
                                {% endif %}
                            {% endwith %}
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    {% if perms.catalog.product_detail %}
                                        <a href="{% url 'catalog:product_detail' product.pk %}"
                                           class="btn btn-sm btn-outline-secondary">Подробнее</a>
                                    {% endif %}
                                    {% if perms.catalog.can_edit_product and perms.catalog.can_edit_description and perms.catalog.can_edit_is_published or user == product.owner %}
                                        <a href="{% url 'catalog:update_product' product.pk %}"
                                           class="btn btn-sm btn-outline-secondary">Изменить</a>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                        <a href="{% url 'catalog:delete_product' product.pk %}"
                                           class="btn btn-sm btn-outline-danger">Удалить</a>
                                    {% endif %}
                                </div>
                                <small class="text-muted">{{ product.price }}</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
    <h2>Удалить продукт "{{ object.name }}"?</h2>
    <div class="confirmation-actions">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger ml-5">Удалить</button>
            <a href="{% url 'catalog:index' %}" class="btn btn-secondary ml-2">Отмена</a>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load media_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <h3 class="card-header">
                        Информация о продукте
                    </h3>
                    <img class="card-img-top"
                         src="{{ object.image|media_url }}"
                         alt="Card image cap">
                </div>
                <div class="col-6">
                    <h2>{{ object.name }}</h2>
                    <p>Цена: {{ object.price }}</p>
                    <p>Описание: {{ object.description }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление продукта
                        </h3>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </form>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Добавление версии
                        </h3>
                    </div>
                    <div class="card-body">
                        {{ formset.management_form }}
                        {% for form in formset.forms %}
                            {{ form.as_p }}
                            {% if not forloop.last %}
                                <hr>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}